version: '2'
services:

  app:
    build: ./app
    volumes:
     - ./app/src:/usr/src/app/src
    environment:
     - CI=true
    command: npm run test:ci

  backend:
    build: ./backend
    volumes:
      - ./backend/src:/usr/src/app/src
    environment:
      - MONGO_DB_URI=mongodb://mongo:27018/backend
      - TEST_REPORT_PATH=./src
    command: npm test