version: '2'
services:

  webserver:
    build: 
      context: ./nginx
      args:
        configfile: staging.conf
    restart: always
    ports:
     - "443:443"
     - "5000:80"
    volumes:
     - static-files:/var/www/src/uploads
    links:
     - backend
     - app

  app:
    image: tommykronstal/2dv612frontend
    ports:
     - "3000:3000"
    links:
     - backend
    volumes:
     - ./app/src:/usr/src/app/src
    command: npm start

  storybook:
    build: ./app
    ports:
     - "9001:9001"
    volumes:
     - ./app/src:/usr/src/app/src
     - ./app/stories:/usr/src/app/stories
    command: npm run storybook

  backend:
    image: tommykronstal/2dv612backend
    volumes:
      - ./backend/src:/usr/src/app/src
      - static-files:/usr/src/app/src/filesystem/uploads/uploads
    ports:
      - "4000:4000"
    links:
      - mongo
    environment:
      - MONGO_DB_URI=mongodb://mongo:27017/backend
    command: npm start

  mongo:
    image: mongo:3.4
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db

volumes:
  static-files: