version: '2'
services:

  webserver:
    build:
      context: ./nginx
      args:
        configfile: site.conf
    restart: always
    ports:
     - "443:443"
     - "80:80"
    volumes:
     - static-files:/var/www/src
    links:
     - backend

  app:
    image: tommykronstal/2dv612frontend
    depends_on:
      - webserver
    volumes:
     - static-files:/usr/src/app/build
    environment:
     - NODE_ENV=production
    command: npm run build

  backend:
    image: tommykronstal/2dv612backend
    ports:
      - "4000:4000"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      - MONGO_DB_URI=mongodb://mongo:27017/backend
      - ADMIN_PASSWORD=$ADMIN_PASSWORD
      - NODE_ENV=production
    command: npm start
    volumes:
    - static-files:/usr/src/app/src/filesystem/uploads

  mongo:
    image: mongo:3.4
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db

volumes:
  static-files:
