version: '3'
services:
  app:
    build: ./app
    ports:
     - "3000:3000"
    volumes:
     - ./app/src:/usr/src/app/src
  storybook:
    build: ./app
    ports:
     - "9001:9001"
    volumes:
     - ./app/src:/usr/src/app/src
    command: npm run storybook
  db:
    image: mongo
    ports:
     - "27017:27017"
  backend:
    build: ./backend
    ports:
      - "4000:4000"
