version: '2'
services:

  app:
    build: ./app
    ports:
     - "3000:3000"
    links:
     - backend
    environment:
     - NODE_ENV=production
    command: npm run serve

  backend:
    build: ./backend
    ports:
      - "4000:4000"
    links:
      - mongo
    environment:
      - MONGO_DB_URI=mongodb://mongo:27017/backend
    command: npm start

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
