version: '2'
services:

  app:
    image: tommykronstal/2dv612frontend
    volumes:
     - ./app/src:/usr/src/app/src
     - ./app/__pacts__:/usr/src/app/__pacts__
    environment:
     - CI=true
    command: npm run test:ci

  backend:
    image: tommykronstal/2dv612backend
    volumes:
      - ./backend/src:/usr/src/app/src
    environment:
      - MONGO_DB_URI=mongodb://mongo:27018/backend
      - TEST_REPORT_PATH=./src
    command: npm test