// STATUS
export const SET_STATUS = 'SET_STATUS'
export const DISMISS_STATUS = 'DISMISS_STATUS'

// LOGIN
export const TOGGLE_LOADING = 'TOGGLE_LOADING'
export const TRY_LOGIN = 'TRY_LOGIN'

// AUTH
export const SET_LOGGED_IN = 'SET_LOGGED_IN'
export const LOGOUT = 'LOGOUT'

// COMPANY
export const FETCH_COMPANIES = 'FETCH_COMPANIES'
export const TRY_ADD_COMPANY = 'TRY_ADD_COMPANY'

// FORM
export const CLEAR_FORM = 'CLEAR_FORM'
export const SUBMIT_FORM = 'SUBMIT_FORM'
export const UPDATE_FIELD = 'UPDATE_FIELD'
