// STATUS
export const SET_STATUS = 'SET_STATUS'
export const DISMISS_STATUS = 'DISMISS_STATUS'

// LOADING
export const TOGGLE_LOADING = 'TOGGLE_LOADING'

// AUTH
export const SET_LOGGED_IN = 'SET_LOGGED_IN'
export const LOGOUT = 'LOGOUT'

// FORM
export const CLEAR_FORM = 'CLEAR_FORM'
export const SUBMIT_FORM = 'SUBMIT_FORM'
export const UPDATE_FIELD = 'UPDATE_FIELD'


// categories
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES'
export const SET_CATEGORIES = 'SET_CATEGORIES'
// NAVIGATION
export const TOGGLE_NAVIGATION = 'TOGGLE_NAVIGATION'

export const FETCH_PRODUCTS = 'FETCH_PRODUCTS'
export const FETCH_PRODUCT = 'FETCH_PRODUCT'
export const SET_PRODUCTS = 'SET_PRODUCTS'
export const SET_PRODUCT = 'SET_PRODUCT'
export const SET_RATING = 'SET_RATING'
export const UPDATE_MATERIAL = 'UPDATE_MATERIAL'
export const UPDATE_ANNOTATION = 'UPDATE_ANNOTATION'
export const UPDATE_PRODUCT_MATERIAL_ANNOTATION = 'UPDATE_PRODUCT_MATERIAL_ANNOTATION'

export const SET_SEARCH_QUERY = 'SET_SEARCH_QUERY'
export const SET_SEARCH_RESULTS = 'SET_SEARCH_RESULTS'
export const FETCH_SEARCH_RESULTS = 'FETCH_SEARCH_RESULTS'