export const UPDATE_TEXT = 'UPDATE_TEXT';
export const SET_STATUS = 'SET_STATUS';
export const DISMISS_STATUS = 'DISMISS_STATUS';
export const UPDATE_WELCOME_MESSAGE = 'UPDATE_WELCOME_MESSAGE';

// LOGIN
export const TOGGLE_LOADING = 'TOGGLE_LOADING'
export const TRY_LOGIN = 'TRY_LOGIN'

// AUTH
export const SET_LOGGED_IN = 'SET_LOGGED_IN'
export const LOGOUT = 'LOGOUT'

//COMPANY
export const ADD_COMPANY = 'ADD_COMPANY'